version: '3.8'

services:
  barracuda:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barracuda
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    working_dir: /app
    tty: true
