/**
 * Common filter options used across different filter types
 * These options are reusable and can be shared between different filters
 */
export const commonOptions = {
  currency: [
    { value: "all", label: "All Currencies", category: "all" },
    { value: "USD", label: "USD", category: "major", symbol: "$" },
    { value: "EUR", label: "EUR", category: "major", symbol: "€" },
    { value: "GBP", label: "GBP", category: "major", symbol: "£" },
    { value: "BGN", label: "BGN", category: "regional", symbol: "лв" },
    { value: "CAD", label: "CAD", category: "major", symbol: "C$" },
    { value: "AUD", label: "AUD", category: "major", symbol: "A$" },
    { value: "JPY", label: "JPY", category: "major", symbol: "¥" },
    { value: "CHF", label: "CHF", category: "regional", symbol: "CHF" },
  ],
  paymentMethod: [
    { value: "all", label: "All Methods", category: "all" },
    { value: "card", label: "Card", category: "card", icon: "CreditCard" },
    { value: "bank_transfer", label: "Bank Transfer", category: "banking", icon: "Building" },
    { value: "wallet", label: "Digital Wallet", category: "digital", icon: "Wallet" },
    { value: "ach", label: "ACH", category: "banking", icon: "Building" },
    { value: "wire", label: "Wire Transfer", category: "banking", icon: "Building" },
  ],
  country: [
    { value: "all", label: "All Countries", region: "all" },
    { value: "US", label: "United States", region: "americas", code: "US" },
    { value: "CA", label: "Canada", region: "americas", code: "CA" },
    { value: "GB", label: "United Kingdom", region: "europe", code: "GB" },
    { value: "DE", label: "Germany", region: "europe", code: "DE" },
    { value: "FR", label: "France", region: "europe", code: "FR" },
    { value: "AU", label: "Australia", region: "apac", code: "AU" },
    { value: "JP", label: "Japan", region: "apac", code: "JP" },
  ],
  industry: [
    { value: "all", label: "All Industries", category: "all" },
    { value: "retail", label: "Retail", category: "commerce" },
    { value: "restaurant", label: "Restaurant", category: "hospitality" },
    { value: "ecommerce", label: "E-commerce", category: "commerce" },
    { value: "services", label: "Services", category: "professional" },
    { value: "healthcare", label: "Healthcare", category: "professional" },
    { value: "education", label: "Education", category: "institutional" },
    { value: "technology", label: "Technology", category: "professional" },
  ],
  role: [
    { value: "all", label: "All Roles", level: "all" },
    { value: "admin", label: "Admin", level: "high", permissions: ["read", "write", "delete"] },
    { value: "manager", label: "Manager", level: "medium", permissions: ["read", "write"] },
    { value: "user", label: "User", level: "low", permissions: ["read"] },
    { value: "viewer", label: "Viewer", level: "minimal", permissions: ["read"] },
  ],
  riskLevel: [
    { value: "all", label: "All Risk Levels", severity: "all" },
    { value: "low", label: "Low", severity: 1, color: "success" },
    { value: "medium", label: "Medium", severity: 2, color: "warning" },
    { value: "high", label: "High", severity: 3, color: "error" },
    { value: "critical", label: "Critical", severity: 4, color: "error" },
  ],
  refundReason: [
    { value: "all", label: "All Reasons", category: "all" },
    { value: "requested_by_customer", label: "Customer Request", category: "customer" },
    { value: "duplicate", label: "Duplicate", category: "error" },
    { value: "fraudulent", label: "Fraudulent", category: "security" },
    { value: "processing_error", label: "Processing Error", category: "error" },
  ],
  disputeReason: [
    { value: "all", label: "All Reasons", category: "all" },
    { value: "fraudulent", label: "Fraudulent", category: "security" },
    { value: "unrecognized", label: "Unrecognized", category: "customer" },
    { value: "duplicate", label: "Duplicate", category: "error" },
    { value: "subscription_canceled", label: "Subscription Canceled", category: "customer" },
    { value: "product_not_received", label: "Product Not Received", category: "fulfillment" },
    { value: "credit_not_processed", label: "Credit Not Processed", category: "processing" },
  ],
  failureReason: [
    { value: "all", label: "All Reasons", category: "all" },
    { value: "insufficient_funds", label: "Insufficient Funds", category: "customer" },
    { value: "card_declined", label: "Card Declined", category: "card" },
    { value: "expired_card", label: "Expired Card", category: "card" },
    { value: "invalid_cvc", label: "Invalid CVC", category: "card" },
    { value: "processing_error", label: "Processing Error", category: "system" },
  ],
  channel: [
    { value: "online", label: "Online", icon: "Globe" },
    { value: "mobile", label: "Mobile", icon: "Smartphone" },
    { value: "pos", label: "Point of Sale", icon: "CreditCard" },
    { value: "api", label: "API", icon: "Code" },
  ],
  programType: [
    { value: "all", label: "All Types", category: "all" },
    { value: "loyalty", label: "Loyalty", category: "customer" },
    { value: "rewards", label: "Rewards", category: "customer" },
    { value: "cashback", label: "Cashback", category: "financial" },
    { value: "points", label: "Points", category: "customer" },
  ],
  store: [
    { value: "all", label: "All Stores" },
    { value: "online", label: "Online" },
    { value: "main_street", label: "Main Street" },
    { value: "airport_kiosk", label: "Airport Kiosk" },
    { value: "flagship", label: "Flagship" },
    { value: "outlet", label: "Outlet" },
  ],
  organization: [
    { value: "all", label: "All Organizations" },
    { value: "org_alpha", label: "Org Alpha" },
    { value: "org_beta", label: "Org Beta" },
    { value: "org_gamma", label: "Org Gamma" },
  ],
  productPlatform: [
    { value: "all", label: "All Product Platforms" },
    { value: "ecommerce", label: "E-commerce" },
    { value: "pos", label: "POS" },
    { value: "mobile", label: "Mobile" },
    { value: "saas", label: "SaaS" },
  ],
  processor: [
    { value: "all", label: "All Processors" },
    { value: "stripe", label: "Stripe" },
    { value: "adyen", label: "Adyen" },
    { value: "worldpay", label: "Worldpay" },
    { value: "checkout", label: "Checkout.com" },
    { value: "paypal", label: "PayPal" },
  ],
  bank: [
    { value: "all", label: "All Banks" },
    { value: "jpmorgan", label: "J.P. Morgan" },
    { value: "bank_of_america", label: "Bank of America" },
    { value: "wells_fargo", label: "Wells Fargo" },
    { value: "citi", label: "Citi" },
    { value: "hsbc", label: "HSBC" },
  ],
} as const 
